// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB624dRUc5CBoD3kyMVqYx5kyEIIOANc-o',
    appId: '1:160308206097:web:fade92b6a3828eedd22fb0',
    messagingSenderId: '160308206097',
    projectId: 'mctask-f96de',
    authDomain: 'mctask-f96de.firebaseapp.com',
    storageBucket: 'mctask-f96de.appspot.com',
    measurementId: 'G-XKHSJB08VF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH4-cOLQN7ekjPciSijPiYaw70VvmfEnU',
    appId: '1:160308206097:android:e49a56985605a9bad22fb0',
    messagingSenderId: '160308206097',
    projectId: 'mctask-f96de',
    storageBucket: 'mctask-f96de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPP2f3OzvWvdtF7eWX514ULYO4Ex7viN0',
    appId: '1:160308206097:ios:efca2e9c2ee2649cd22fb0',
    messagingSenderId: '160308206097',
    projectId: 'mctask-f96de',
    storageBucket: 'mctask-f96de.appspot.com',
    iosBundleId: 'com.example.mctask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPP2f3OzvWvdtF7eWX514ULYO4Ex7viN0',
    appId: '1:160308206097:ios:1a00a9df7b603344d22fb0',
    messagingSenderId: '160308206097',
    projectId: 'mctask-f96de',
    storageBucket: 'mctask-f96de.appspot.com',
    iosBundleId: 'com.example.mctask.RunnerTests',
  );
}
